In [1]:
import pandas as pd

## Drop and remove duplicates

In [3]:
data={"A":["teamA","teamB","teamB","teamC","teamA"],
     "B":[50,40,40,30,50],
     "C":[True,False,False,False,True]}
df=pd.DataFrame(data)
df

       A   B      C
0  teamA  50   True
1  teamB  40  False
2  teamB  40  False
3  teamC  30  False
4  teamA  50   True

In [5]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [6]:
df.duplicated(keep="first")

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [7]:
df.duplicated(keep="last")  #checks from the last

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [10]:
 df.duplicated(keep=False)  #gives true in all duplicates

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [11]:
df.drop_duplicates()

       A   B      C
0  teamA  50   True
1  teamB  40  False
3  teamC  30  False

In [12]:
df.drop_duplicates(keep="last")

       A   B      C
2  teamB  40  False
3  teamC  30  False
4  teamA  50   True

In [13]:
df.drop_duplicates(keep=False)

       A   B      C
3  teamC  30  False

In [14]:
df.drop_duplicates(keep="first",inplace=True)

In [15]:
df.reset_index(drop=True)

       A   B      C
0  teamA  50   True
1  teamB  40  False
2  teamC  30  False

In [16]:
a=pd.read_csv('auto-mpg.csv')
pd.crosstab(a['cylinders'], a['model year'], rownames=['cylinders'], colnames=['model year'],margins=True)

model year  70  71  72  73  74  75  76  77  78  79  80  81  82  All
cylinders
3            0   0   1   1   0   0   0   1   0   0   1   0   0    4
4            7  13  14  11  15  12  15  14  17  12  25  21  28  204
5            0   0   0   0   0   0   0   0   1   1   1   0   0    3
6            4   8   0   8   7  12  10   5  12   6   2   7   3   84
8           18   7  13  20   5   6   9   8   6  10   0   1   0  103
All         29  28  28  40  27  30  34  28  36  29  29  29  31  398

### sort_values

In [27]:
data={"Name":["Alice","Bob","Charlie","David"],
     "Score":[88,92,95,90]}
df=pd.DataFrame(data)
df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     95
3    David     90

In [28]:
sorted_df=df.sort_values(by="Score")
sorted_df

      Name  Score
0    Alice     88
3    David     90
1      Bob     92
2  Charlie     95

In [29]:
sorted_df=df.sort_values(by="Score",ascending=False)
sorted_df

      Name  Score
2  Charlie     95
1      Bob     92
3    David     90
0    Alice     88

In [30]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     95
1      Bob     92
0    Alice     88

In [31]:
df.set_index("Name",inplace=True)

In [32]:
df

         Score
Name
Alice       88
Bob         92
Charlie     95
David       90

In [33]:
df.sort_index(ascending=True)

         Score
Name
Alice       88
Bob         92
Charlie     95
David       90

### apply()

In [43]:
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return "pass" if x>=50 else "Fail"

result=s.apply(pass_fail)
print(result)

0    Fail
1    pass
2    pass
3    Fail
dtype: object

In [44]:
df2=pd.DataFrame({
    "phy":[60,70,80],
    "chem":[65,75,85],
    "maths":[70,80,90]
})

result=df2.apply(sum)
print(result)

phy      210
chem     225
maths    240
dtype: int64

In [45]:
df2=pd.DataFrame({
    "phy":[60,70,80],
    "chem":[65,75,85],
    "maths":[70,80,90]
})

result=df2.apply(sum,axis=1)
print(result)

0    195
1    225
2    255
dtype: int64

In [46]:
df2=pd.DataFrame({
    "phy":[60,70,80],
    "chem":[65,75,85],
    "maths":[70,80,90]
})

result=df2.apply(lambda x:x.mean())
print(result)

phy      70.0
chem     75.0
maths    80.0
dtype: float64

In [49]:
df2

   phy  chem  maths
0   60    65     70
1   70    75     80
2   80    85     90

In [50]:
df2["total"]=df2.apply(lambda x:x.sum(),axis=1)
df2

   phy  chem  maths  total
0   60    65     70    195
1   70    75     80    225
2   80    85     90    255

In [52]:
def grade(total):
    if total>=250:
        return "A"
    elif total>=200:
        return "B"
    else:
        return "C"

In [54]:
df2["grade"]=df2["total"].apply(grade)

In [55]:
df2

   phy  chem  maths  total grade
0   60    65     70    195     C
1   70    75     80    225     B
2   80    85     90    255     A

In [63]:
d=pd.DataFrame({"width":[1,2], "height":[3,4]})
def get_stats(row):
    return [row['width']*row['height'], 2*(row['width']+row['height'])]
d

   width  height
0      1       3
1      2       4

In [64]:
d.apply(get_stats, axis=1)  #output same as result_type="reduce"

0     [3, 8]
1    [8, 12]
dtype: object

In [65]:
d.apply(get_stats, axis=1, result_type="expand")

   0   1
0  3   8
1  8  12

In [66]:
d.apply(get_stats, axis=1, result_type="broadcast")

   width  height
0      3       8
1      8      12

##  args & kwargs

In [68]:
def add_values(x,y,z):
    return x+y+z

d=pd.DataFrame({"A":[1,2],"B":[10,20]})
d1=d.apply(add_values, args=(1,2))
print(d1)

   A   B
0  4  13
1  5  23

In [71]:
def multiply(x,m):
    return x*m

d=pd.DataFrame({"A":[1,2],"B":[10,20]})
d1=d.apply(multiply,m=10)
print(d1)

    A    B
0  10  100
1  20  200

In [72]:
a=pd.DataFrame({"A":["1","2","3"],"B":["4","5","6"]})
print(a.dtypes)

A    object
B    object
dtype: object

In [73]:
a["A"]=a["A"].astype(int)
print(a.dtypes)

A     int32
B    object
dtype: object

In [74]:
b=pd.DataFrame({
    "marks":[80,85,0,90],
    "attd":[75,80,0,85],
    "grade":["A","B","F","A"]
})
print(b)
print()
result=b.replace([80,75],[90,80])
print(result)

   marks  attd grade
0     80    75     A
1     85    80     B
2      0     0     F
3     90    85     A

   marks  attd grade
0     90    80     A
1     85    90     B
2      0     0     F
3     90    85     A

In [75]:
b=pd.DataFrame({
    "marks":[80,85,0,90],
    "attd":[75,80,0,85],
    "grade":["A","B","F","A"]
})
print(b)
print()
result=b.replace({80:90,85:80})
print(result)

   marks  attd grade
0     80    75     A
1     85    80     B
2      0     0     F
3     90    85     A

   marks  attd grade
0     90    75     A
1     80    90     B
2      0     0     F
3     90    80     A

In [76]:
b["marks"]=b["marks"].replace(0,50)
b

   marks  attd grade
0     80    75     A
1     85    80     B
2     50     0     F
3     90    85     A

In [77]:
b["attd"]=b["attd"].replace(0,60)
b

   marks  attd grade
0     80    75     A
1     85    80     B
2     50    60     F
3     90    85     A

In [79]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"A":[5,6],"C":[7,8]})

r=pd.concat([c1,c2],axis=0)
r

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [80]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"A":[5,6],"C":[7,8]})

r=pd.concat([c1,c2],axis=1)
r

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [81]:
pd.concat([c1,c2], join="outer")

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [82]:
pd.concat([c1,c2], join="inner") #only keeps overlaps

   A
0  1
1  2
0  5
1  6

In [83]:
pd.concat([c1,c2], join="inner", ignore_index=True) #resets index to 0,1,2,3

   A
0  1
1  2
2  5
3  6

In [86]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"C":[5,6],"D":[7,8]})

r=pd.concat([c1,c2],sort=False)
r

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [87]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"C":[5,6],"D":[7,8]})

r=pd.concat([c1,c2],sort=True)
r

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [88]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"C":[5,6],"D":[7,8]})

r=pd.concat([c1,c2],sort=False,axis=1)
r

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

In [89]:
c1=pd.DataFrame({"A":[1,2],"B":[3,4]})
c2=pd.DataFrame({"C":[5,6],"D":[7,8]})

r=pd.concat([c1,c2],sort=True,axis=1)
r

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

## merge                                                                                                                                       
pd.merge(left, right, how="inner or on=None, right_on=None)

In [90]:
e1=pd.DataFrame({
    "emp":["a","b","c"],
    "dep":["it","hr","finance"]
})

e2=pd.DataFrame({
    "emp":["a","b","d"],
    "sal":[50000,40000,30000]
})

r=pd.merge(e1,e2,on="emp",how="inner")
r

  emp dep    sal
0   a  it  50000
1   b  hr  40000

In [91]:
r1=pd.merge(e1,e2,on="emp",how="outer")
r1

  emp      dep      sal
0   a       it  50000.0
1   b       hr  40000.0
2   c  finance      NaN
3   d      NaN  30000.0

In [92]:
r1=pd.merge(e1,e2,on="emp",how="left")
r1

  emp      dep      sal
0   a       it  50000.0
1   b       hr  40000.0
2   c  finance      NaN

In [93]:
r1=pd.merge(e1,e2,on="emp",how="right")
r1

  emp  dep    sal
0   a   it  50000
1   b   hr  40000
2   d  NaN  30000