In [1]:
import pandas as pd

In [4]:
a1=pd.DataFrame({
    "id":[1,2,3],
    "name":["amit","riya","john"],
    "salary":[50000,60000,55000]
})

a2=pd.DataFrame({
    "id":[1,2,4],
    "name":["amit","riya","david"],
    "salary":[50000,60000,58000]
})

r=pd.merge(a1,a2,on="id",suffixes=("_left","_right"))
print(r)

   id name_left  salary_left name_right  salary_right
0   1      amit        50000       amit         50000
1   2      riya        60000       riya         60000

In [2]:
b1=pd.DataFrame({"student":[1,2,3],
                "name":["amit","ria","john"]})
b2=pd.DataFrame({"id":[1,2,4],
                "marks":[80,90,75]})
r1=pd.merge(b1,b2,left_on="student",right_on="id")
print(r1)

   student  name  id  marks
0        1  amit   1     80
1        2   ria   2     90

In [9]:
c1=pd.DataFrame({"physics":[70,80,90]},index=[101,102,103])
c2=pd.DataFrame({"name":["alice","bob","charlie"]},index=[101,102,103])
r2=pd.merge(c1,c2,left_index=True,right_index=True)
print(r2)

     physics     name
101       70    alice
102       80      bob
103       90  charlie

In [12]:
d1=pd.DataFrame({"student":[1,2,3],
                "name":["amit","ria","john"]})
d2=pd.DataFrame({"score":[70,80,90]},index=[1,2,3])
r3=pd.merge(d1,d2,left_on="student",right_index=True)
print(r3)

   student  name  score
0        1  amit     70
1        2   ria     80
2        3  john     90

## groupby

In [13]:
data={"product":["electronics","furniture","electronics","furniture"],
     "sales":[200,150,300,100]}
df=pd.DataFrame(data)
df

       product  sales
0  electronics    200
1    furniture    150
2  electronics    300
3    furniture    100

In [15]:
r=df.groupby("product")["sales"].sum()
print(r)

product
electronics    500
furniture      250
Name: sales, dtype: int64

In [16]:
r=df.groupby("product")["sales"].mean()
print(r)

product
electronics    250
furniture      125
Name: sales, dtype: int64

In [17]:
r=df.groupby("product")["sales"].median()
print(r)

product
electronics    250
furniture      125
Name: sales, dtype: int64

In [18]:
r=df.groupby("product")["sales"].describe()
print(r)

             count   mean        std    min    25%    50%    75%    max
product
electronics    2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
furniture      2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [19]:
r=df.groupby("product")["sales"].sample()
print(r)

2    300
1    150
Name: sales, dtype: int64

In [20]:
r=df.groupby("product")["sales"].size()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [22]:
r=df.groupby("product")["sales"].groups
print(r)

{'electronics': [0, 2], 'furniture': [1, 3]}

In [23]:
r=df.groupby("product")["sales"].nunique()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [24]:
r=df.groupby("product")["sales"].nth(0)
print(r)

product
electronics    200
furniture      150
Name: sales, dtype: int64

In [26]:
r=df.groupby("product")["sales"].nth(1)
print(r)

product
electronics    300
furniture      100
Name: sales, dtype: int64

In [27]:
r=df.groupby("product",axis=0,as_index=True,sort=True)["sales"].count()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [28]:
r=df.groupby("product",axis=0,as_index=False,sort=True)["sales"].count()
print(r)

       product  sales
0  electronics      2
1    furniture      2

In [30]:
e1=pd.DataFrame({"region":["east","east","west","west","east","west"],
               "sales":[100,150,200,120,110,130],
               "manager":["a","b","c","d","e","f"]})
e1

  region  sales manager
0   east    100       a
1   east    150       b
2   west    200       c
3   west    120       d
4   east    110       e
5   west    130       f

In [31]:
def sales_range(group):
    return group["sales"].max()-group["sales"].min()     #max-min
sales=e1.groupby("region").apply(sales_range)
print(sales)

region
east    50
west    80
dtype: int64

In [33]:
e2=pd.DataFrame({"dept":['sales','sales','hr','hr','it','it'],
                "salary":[50000,60000,40000,45000,70000,75000],
                "bonus":[5000,6000,2000,2500,8000,8500]})
r5=e2.groupby("dept").agg('mean')
print(r5)

       salary  bonus
dept
hr      42500   2250
it      72500   8250
sales   55000   5500

In [36]:
e2=pd.DataFrame({"dept":['sales','sales','hr','hr','it','it'],
                "salary":[50000,60000,40000,45000,70000,75000],
                "bonus":[5000,6000,2000,2500,8000,8500]})
r5=e2.groupby("dept").agg(['mean','min','max'])
print(r5)

      salary               bonus
        mean    min    max  mean   min   max
dept
hr     42500  40000  45000  2250  2000  2500
it     72500  70000  75000  8250  8000  8500
sales  55000  50000  60000  5500  5000  6000

In [37]:
e2=pd.DataFrame({"dept":['sales','sales','hr','hr','it','it'],
                "salary":[50000,60000,40000,45000,70000,75000],
                "bonus":[5000,6000,2000,2500,8000,8500]})
r5=e2.groupby("dept").agg({'salary':['min','max'],
                           'bonus':'sum'})
print(r5)

      salary         bonus
         min    max    sum
dept
hr     40000  45000   4500
it     70000  75000  16500
sales  50000  60000  11000

In [40]:
e2=pd.DataFrame({"dept":['sales','sales','hr','hr','it','it'],
                "salary":[50000,60000,40000,45000,70000,75000],
                "bonus":[5000,6000,2000,2500,8000,8500]})
r5=e2.groupby("dept").agg(meansalary=('salary','mean'),
                          maxsalary=('salary','max'),
                         totalbonus=('bonus','sum'))
print(r5)

       meansalary  maxsalary  totalbonus
dept
hr          42500      45000        4500
it          72500      75000       16500
sales       55000      60000       11000