In [1]:
from bs4 import BeautifulSoup
import requests

In [22]:
url="https://www.politifact.com/factchecks/"
result=requests.get(url)
content=result.text
soup=BeautifulSoup(content,'html.parser')
# print(soup.prettify())

In [23]:
data=soup.find_all('li',class_='o-listicle__item')
# data

In [24]:
data[0]

<li class="o-listicle__item">
<article class="m-statement m-statement--is-medium m-statement--false">
<div class="m-statement__author">
<div class="m-statement__avatar">
<div class="m-statement__image">
<div class="c-image" style="padding-top: 119.27710843373494%;">
<img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg" width="83"/>
<picture>
<img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg" width="166"/>
</picture>
</div>
</div>
</div>
<div class="m-statement__meta">
<a class="m-statement__name" href="/personalities/donald-trump/" title="Donald Trump">
                    Donald Trump
                  </a>
<div class="m-statement__desc">
                    stated on May 18, 2026 in remarks at the White House:
                  </div>
</div>
</div>
<div class="m-statement__content">
<div class="m-statement__body">
<div class="m-statement__quote-wrap">
<div class="m-statement__quote">
<a href="/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/">

                        "There's been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.

                      </a>
</div>
</div>
<div class="m-statement__meter">
<div class="c-image" style="padding-top: 89.49771689497716%;">
<img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
<picture>
<img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
</picture>
</div>
</div>
<footer class="m-statement__footer">
                    By Louis Jacobson • May 20, 2026
                  </footer>
</div>
</div>
</article>
</li>

In [25]:
data[0].find('div',class_='m-statement__meta').find('a').text.strip()

'Donald Trump'

In [26]:
source=[]
for i in data:
    source.append(i.find('div',class_='m-statement__meta').find('a').text.strip())
print(source)

['Donald Trump', 'Social Media', 'X posts', 'X posts', 'Kathy Castor', 'Vivek Ramaswamy', 'TikTok posts', 'Christine Quinn', 'Nicholas Langworthy', 'Donald Trump', 'Byron Donalds', 'Marcy Kaptur', 'Liz Krueger', 'X posts', 'Donald Trump', 'Sam Sutton', 'Fentrice Driskell', 'Instagram posts', 'Bernie Sanders', 'Tim Scott', 'Pine Tree Results PAC', 'Social Media', 'Donald Trump', 'Ron DeSantis', 'Social Media', 'Jay Collins', 'Robert F. Kennedy Jr.', 'Joe Rogan', 'X posts', 'Chris Wright']

In [27]:
statement=[]
for i in data:
    statement.append(i.find('div',class_='m-statement__quote').text.strip())
print(statement)

['"There\'s been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.', '“San Diego mosque shooters identified as trans couple.”', 'Video shows U.S. Rep. Byron Donalds saying, “Insider trading should absolutely be allowed for members of Congress.”', 'An American passenger on the cruise ship involved in the hantavirus outbreak is a "crisis actor."', '“Florida is the only state in the nation kicking children off their affordable health coverage.”', 'In 2020, “Amy Acton called off Ohio’s election at the last minute.”', 'Imágenes muestran a personas “infectadas con Hantavirus”.', '“Today, there are more children sleeping in New York City’s homeless shelters than there are seats in Yankee Stadium.”', '“The average IRS tax refund is up 11% compared to last year.”', 'Gasoline prices have “come down very substantially today.”', 'Congress passed the 1965 Voting Rights Act because “the Democrat party at the time, especially in the South, were racially gerrymandering districts to disenfranchise Black voters.”', 'Republicans “want you to pay $1 Billion for a ballroom.”', 'Proposed data centers in New York state would use “approximately double the energy usage of all households in the state combined.”', '“California only has ‘enough’ oil and gas supply to meet demand for the next six weeks.”', '“Consumer confidence is way up."', 'From January 2025 to January 2026, “hate crimes in New York City increased by 152%”', '“Under federal law, you cannot engage in partisan gerrymandering.”', 'Imagen muestra que “950 inmigrantes derrumbaron el muro fronterizo entre México y Estados Unidos intentando ingresar a Estados Unidos” en abril 2026.', '“As a result of the \'Big Beautiful Bill\' 15 million Americans have been thrown off the healthcare that they need."', '“Secret Service remains unpaid” during the partial government shutdown.', '“Graham Platner blames Maine’s women for getting raped because he says they get f----- up drunk"', 'Video shows “unedited raw security footage” of the shooter at the April 25 White House Correspondents’ Association dinner.', '“We are right now producing more oil than Saudi Arabia and Russia combined.”', 'Since the 2020 census, Florida has "moved from a Democrat majority to a 1.5 million Republican advantage."', '“Tras el atentado a Trump”, en la cena de corresponsales de la Casa Blanca el 25 de abril, “Irán lanza un mensaje fuerte: ‘no le crean nada, miente’”.', 'U.S. Rep. Byron Donalds voted "against three pay raises for military service members, including the largest pay raise for the military in 22 years."', '"There\'s two ways of calculating percentage" decreases. “If you have a $600 drug and you reduce it to $10, that\'s a 600% reduction."', "“With one dose of ibogaine, more than 80% of people are free of (opioid) addiction. With two doses, it's more than 90%.”", "“Newly released FOIA door logs show that former President Joe Biden didn't enter the Oval Office once after the 2024 election.”", 'Solar and wind have not reached “3% of global energy.”']

In [28]:
date=[]
for i in data:
    date.append(i.find('footer',class_='m-statement__footer').text.strip())
print(date)

['By Louis Jacobson • May 20, 2026', 'By Jeff Cercone • May 20, 2026', 'By Loreben Tuquero • May 15, 2026', 'By Maria Briceño • May 14, 2026', 'By Samantha Putterman • May 14, 2026', 'By Amy Sherman • May 13, 2026', 'By Maria Briceño • May 13, 2026', 'By Andrew McGurl • May 11, 2026', 'By Holden Turek • May 11, 2026', 'By Louis Jacobson • May 8, 2026', 'By Samantha Putterman • May 8, 2026', 'By Maria Briceño • May 8, 2026', 'By Conor Amendola • May 7, 2026', 'By Louis Jacobson • May 7, 2026', 'By Louis Jacobson • May 6, 2026', 'By Emma Gavazzi • May 5, 2026', 'By Samantha Putterman • May 1, 2026', 'By Maria Briceño • April 30, 2026', 'By Amy Sherman • April 30, 2026', 'By Louis Jacobson • April 29, 2026', 'By Amy Sherman • April 29, 2026', 'By Maria Briceño • April 29, 2026', 'By Louis Jacobson • April 29, 2026', 'By Louis Jacobson • April 29, 2026', 'By Maria Briceño • April 28, 2026', 'By Samantha Putterman • April 23, 2026', 'By Louis Jacobson • April 23, 2026', 'By Grace Abels • April 22, 2026', 'By Maria Briceño • April 22, 2026', 'By Louis Jacobson • April 22, 2026']

In [29]:
date=[]
for i in data:
    date.append(i.find('footer',class_='m-statement__footer').text.split(' • ')[-1].strip())
print(date)

['May 20, 2026', 'May 20, 2026', 'May 15, 2026', 'May 14, 2026', 'May 14, 2026', 'May 13, 2026', 'May 13, 2026', 'May 11, 2026', 'May 11, 2026', 'May 8, 2026', 'May 8, 2026', 'May 8, 2026', 'May 7, 2026', 'May 7, 2026', 'May 6, 2026', 'May 5, 2026', 'May 1, 2026', 'April 30, 2026', 'April 30, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 28, 2026', 'April 23, 2026', 'April 23, 2026', 'April 22, 2026', 'April 22, 2026', 'April 22, 2026']

In [34]:
links=[]
root='https://www.politifact.com'
for i in data:
    d=i.find('div',class_='m-statement__quote').find('a')['href'].strip()
    links.append(root+d)
print(links)

['https://www.politifact.com/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/', 'https://www.politifact.com/factchecks/2026/may/20/social-media/no-evidence-san-diego-mosque-suspects-trans/', 'https://www.politifact.com/factchecks/2026/may/15/tweets/byron-donalds-florida-insider-trading/', 'https://www.politifact.com/factchecks/2026/may/14/tweets/hantavirus-quarantine-crisis-actor-rosmarin/', 'https://www.politifact.com/factchecks/2026/may/14/kathy-castor/kid-care-florida-desantis-health-insurance/', 'https://www.politifact.com/factchecks/2026/may/13/vivek-ramaswamy/Amy-Acton-Ohio-2020-covid-primary-senate/', 'https://www.politifact.com/factchecks/2026/may/13/tiktok-posts/hantavirus-infectados-imagenes-crucero/', 'https://www.politifact.com/factchecks/2026/may/11/christine-quinn/new-york-city-homeless-children-yankee-stadium/', 'https://www.politifact.com/factchecks/2026/may/11/nicholas-langworthy/tax-refunds-11-percent-reduction-irs/', 'https://www.politifact.com/factchecks/2026/may/08/donald-trump/gasoline-prices-falling-crude-oil/', 'https://www.politifact.com/factchecks/2026/may/08/byron-donalds/florida-voting-rights-act-democrats-gerrymandering/', 'https://www.politifact.com/factchecks/2026/may/08/marcy-kaptur/White-House-Trump-ballroom-East-Wing-1-billion/', 'https://www.politifact.com/factchecks/2026/may/07/liz-krueger/electricity-data-centers-new-york-households/', 'https://www.politifact.com/factchecks/2026/may/07/tweets/california-gasoline-supply-six-weeks/', 'https://www.politifact.com/factchecks/2026/may/06/donald-trump/consumer-confidence-sentiment-spending-second-term/', 'https://www.politifact.com/factchecks/2026/may/05/sam-sutton/hate-crimes-new-york-city-houses-worship/', 'https://www.politifact.com/factchecks/2026/may/01/fentrice-driskell/what-does-federal-law-say-about-partisan-gerrymand/', 'https://www.politifact.com/factchecks/2026/apr/30/instagram-posts/muro-fronterizo-inmigrantes-eeuu-mexico-ia/', 'https://www.politifact.com/factchecks/2026/apr/30/bernie-sanders/one-big-beautiful-bill-ACA-health-care-Medicaid/', 'https://www.politifact.com/factchecks/2026/apr/29/tim-scott/secret-service-assassination-shutdown-paychecks/', 'https://www.politifact.com/factchecks/2026/apr/29/pine-tree-results-pac/Graham-Platner-Collins-Maine-reddit-rape-Senate/', 'https://www.politifact.com/factchecks/2026/apr/29/social-media/correspodents-dinner-shooter-security-footage-AI/', 'https://www.politifact.com/factchecks/2026/apr/29/donald-trump/oil-united-states-russia-saudi-arabia-hormuz-iran/', 'https://www.politifact.com/factchecks/2026/apr/29/ron-desantis/florida-redistricting-republican-democrat-majority/', 'https://www.politifact.com/factchecks/2026/apr/28/social-media/Iran-Trump-tiroteo-cena-casa-blanca/', 'https://www.politifact.com/factchecks/2026/apr/23/jay-collins/byron-donalds-florida-military-pay-votes/', 'https://www.politifact.com/factchecks/2026/apr/23/robert-f-kennedy-jr/percentage-decreases-drug-prices-trump-math/', 'https://www.politifact.com/factchecks/2026/apr/22/joe-rogan/ibogaine-opioid-addiction-psychedelic-withdrawal/', 'https://www.politifact.com/factchecks/2026/apr/22/tweets/Biden-Oval-Office-2024-elections/', 'https://www.politifact.com/factchecks/2026/apr/22/chris-wright/wind-solar-energy-oil-strait-hormuz-iran/']

In [35]:
import pandas as pd

In [38]:
df=pd.DataFrame({'Statement':statement, 'Source':source,'Date':date,'Links':links})
df

,Statement,Source,Date,Links
0,"""There's been numerous other occasions over th...",Donald Trump,"May 20, 2026",https://www.politifact.com/factchecks/2026/may...
1,“San Diego mosque shooters identified as trans...,Social Media,"May 20, 2026",https://www.politifact.com/factchecks/2026/may...
2,"Video shows U.S. Rep. Byron Donalds saying, “I...",X posts,"May 15, 2026",https://www.politifact.com/factchecks/2026/may...
3,An American passenger on the cruise ship invol...,X posts,"May 14, 2026",https://www.politifact.com/factchecks/2026/may...
4,“Florida is the only state in the nation kicki...,Kathy Castor,"May 14, 2026",https://www.politifact.com/factchecks/2026/may...
5,"In 2020, “Amy Acton called off Ohio’s election...",Vivek Ramaswamy,"May 13, 2026",https://www.politifact.com/factchecks/2026/may...
6,Imágenes muestran a personas “infectadas con H...,TikTok posts,"May 13, 2026",https://www.politifact.com/factchecks/2026/may...
7,"“Today, there are more children sleeping in Ne...",Christine Quinn,"May 11, 2026",https://www.politifact.com/factchecks/2026/may...
8,“The average IRS tax refund is up 11% compared...,Nicholas Langworthy,"May 11, 2026",https://www.politifact.com/factchecks/2026/may...
9,Gasoline prices have “come down very substanti...,Donald Trump,"May 8, 2026",https://www.politifact.com/factchecks/2026/may...
10,Congress passed the 1965 Voting Rights Act bec...,Byron Donalds,"May 8, 2026",https://www.politifact.com/factchecks/2026/may...
11,Republicans “want you to pay $1 Billion for a ...,Marcy Kaptur,"May 8, 2026",https://www.politifact.com/factchecks/2026/may...
12,Proposed data centers in New York state would ...,Liz Krueger,"May 7, 2026",https://www.politifact.com/factchecks/2026/may...
13,“California only has ‘enough’ oil and gas supp...,X posts,"May 7, 2026",https://www.politifact.com/factchecks/2026/may...
14,"“Consumer confidence is way up.""",Donald Trump,"May 6, 2026",https://www.politifact.com/factchecks/2026/may...
15,"From January 2025 to January 2026, “hate crime...",Sam Sutton,"May 5, 2026",https://www.politifact.com/factchecks/2026/may...
16,"“Under federal law, you cannot engage in parti...",Fentrice Driskell,"May 1, 2026",https://www.politifact.com/factchecks/2026/may...
17,Imagen muestra que “950 inmigrantes derrumbaro...,Instagram posts,"April 30, 2026",https://www.politifact.com/factchecks/2026/apr...
18,“As a result of the 'Big Beautiful Bill' 15 mi...,Bernie Sanders,"April 30, 2026",https://www.politifact.com/factchecks/2026/apr...
19,“Secret Service remains unpaid” during the par...,Tim Scott,"April 29, 2026",https://www.politifact.com/factchecks/2026/apr...
20,“Graham Platner blames Maine’s women for getti...,Pine Tree Results PAC,"April 29, 2026",https://www.politifact.com/factchecks/2026/apr...
21,Video shows “unedited raw security footage” of...,Social Media,"April 29, 2026",https://www.politifact.com/factchecks/2026/apr...
22,“We are right now producing more oil than Saud...,Donald Trump,"April 29, 2026",https://www.politifact.com/factchecks/2026/apr...
23,"Since the 2020 census, Florida has ""moved from...",Ron DeSantis,"April 29, 2026",https://www.politifact.com/factchecks/2026/apr...
24,"“Tras el atentado a Trump”, en la cena de corr...",Social Media,"April 28, 2026",https://www.politifact.com/factchecks/2026/apr...
25,"U.S. Rep. Byron Donalds voted ""against three p...",Jay Collins,"April 23, 2026",https://www.politifact.com/factchecks/2026/apr...
26,"""There's two ways of calculating percentage"" d...",Robert F. Kennedy Jr.,"April 23, 2026",https://www.politifact.com/factchecks/2026/apr...
27,"“With one dose of ibogaine, more than 80% of p...",Joe Rogan,"April 22, 2026",https://www.politifact.com/factchecks/2026/apr...
28,“Newly released FOIA door logs show that forme...,X posts,"April 22, 2026",https://www.politifact.com/factchecks/2026/apr...
29,Solar and wind have not reached “3% of global ...,Chris Wright,"April 22, 2026",https://www.politifact.com/factchecks/2026/apr...

In [39]:
df.to_excel('politifact.xlsx')

In [70]:
s=BeautifulSoup(open('politifact.html','r',encoding='utf-8'))
# print(s.prettify())

In [46]:
upperframe=[]
for page in range(1,5):
    url='https://www.politifact.com/factchecks/?page'+str(page)
    result=requests.get(url)
    content=result.text
    s=BeautifulSoup(content,'html.parser')
    frame=[]
    data=s.find_all('li',class_='o-listicle__item')
    for i in data:
        source=i.find('div',class_='m-statement__meta').find('a').text.strip()
        statement=i.find('div',class_='m-statement__quote').text.strip()
        date=i.find('footer',class_='m-statement__footer').text.split(' • ')[-1].strip()
        links='https://www.politifact.com'+i.find('div',class_='m-statement__quote').find('a')['href'].strip()
        frame.append((statement,source,date,links))
    upperframe.extend(frame)
print(len(upperframe))

120

In [69]:
s=BeautifulSoup(open('top250.html','r',encoding='utf-8'))
# print(s.prettify())

In [53]:
movie=s.find_all('td',class_='titleColumn')
len(movie)

250

In [54]:
movie[0]

<td class="titleColumn">
      1.
      <a href="/title/tt0111161/?pf_rd_m=A2FGELUUNOQJNL&amp;pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&amp;pf_rd_r=3AQ5G29EBVVKV41WYCWB&amp;pf_rd_s=center-1&amp;pf_rd_t=15506&amp;pf_rd_i=top&amp;ref_=chttp_tt_1" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">The Shawshank Redemption</a>
<span class="secondaryInfo">(1994)</span>
</td>

In [57]:
title=[]
for i in movie:
    title.append(i.find('a').text.strip())
print(title)

['The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'The Godfather Part II', '12 Angry Men', "Schindler's List", 'The Lord of the Rings: The Return of the King', 'Pulp Fiction', 'The Lord of the Rings: The Fellowship of the Ring', 'The Good, the Bad and the Ugly', 'Spider-Man: Across the Spider-Verse', 'Forrest Gump', 'Fight Club', 'The Lord of the Rings: The Two Towers', 'Inception', 'Star Wars: Episode V - The Empire Strikes Back', 'The Matrix', 'Goodfellas', "One Flew Over the Cuckoo's Nest", 'Se7en', "It's a Wonderful Life", 'Seven Samurai', 'The Silence of the Lambs', 'Saving Private Ryan', 'City of God', 'Interstellar', 'Life Is Beautiful', 'The Green Mile', 'Star Wars: Episode IV - A New Hope', 'Terminator 2: Judgment Day', 'Back to the Future', 'Spirited Away', 'The Pianist', 'Psycho', 'Parasite', 'Léon: The Professional', 'The Lion King', 'Gladiator', 'American History X', 'The Departed', 'Whiplash', 'The Prestige', 'The Usual Suspects', 'Casablanca', 'Grave of the Fireflies', 'Harakiri', 'The Intouchables', 'Modern Times', 'Once Upon a Time in the West', 'Cinema Paradiso', 'Rear Window', 'Alien', 'City Lights', 'Apocalypse Now', 'Memento', 'Django Unchained', 'Indiana Jones and the Raiders of the Lost Ark', 'WALL·E', 'The Lives of Others', 'Sunset Blvd.', 'Paths of Glory', 'Avengers: Infinity War', 'The Shining', 'The Great Dictator', 'Witness for the Prosecution', 'Spider-Man: Into the Spider-Verse', 'Aliens', 'American Beauty', 'The Dark Knight Rises', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Inglourious Basterds', 'Oldboy', 'Coco', 'Amadeus', 'Toy Story', 'Braveheart', 'Das Boot', 'Joker', 'Avengers: Endgame', 'Princess Mononoke', 'Good Will Hunting', 'Once Upon a Time in America', 'Your Name.', '3 Idiots', "Singin' in the Rain", 'High and Low', 'Requiem for a Dream', 'Capernaum', 'Toy Story 3', 'Star Wars: Episode VI - Return of the Jedi', 'Come and See', 'Eternal Sunshine of the Spotless Mind', '2001: A Space Odyssey', 'The Hunt', 'Reservoir Dogs', 'Lawrence of Arabia', 'Citizen Kane', 'M', 'Ikiru', 'North by Northwest', 'The Apartment', 'Vertigo', 'Amélie', 'Double Indemnity', 'A Clockwork Orange', 'Full Metal Jacket', 'Hamilton', 'Scarface', 'Incendies', 'Heat', 'Up', 'To Kill a Mockingbird', 'The Sting', 'A Separation', 'Metropolis', 'L.A. Confidential', 'Die Hard', 'Indiana Jones and the Last Crusade', 'Snatch', 'Taxi Driver', 'Bicycle Thieves', 'Like Stars on Earth', '1917', 'Dangal', 'Downfall', 'Top Gun: Maverick', 'For a Few Dollars More', 'Batman Begins', 'The Kid', 'Some Like It Hot', 'The Father', 'The Wolf of Wall Street', 'All About Eve', 'Green Book', 'Judgment at Nuremberg', 'Ran', 'The Truman Show', 'Casino', 'There Will Be Blood', "Pan's Labyrinth", 'Unforgiven', 'Shutter Island', 'The Sixth Sense', 'Jurassic Park', 'A Beautiful Mind', 'The Treasure of the Sierra Madre', 'Yojimbo', 'Monty Python and the Holy Grail', 'No Country for Old Men', 'Kill Bill: Vol. 1', 'The Great Escape', 'Rashomon', 'The Thing', 'Finding Nemo', 'Spider-Man: No Way Home', 'The Elephant Man', 'Chinatown', 'Raging Bull', 'V for Vendetta', 'Gone with the Wind', 'Dial M for Murder', 'Inside Out', 'Lock, Stock and Two Smoking Barrels', "Howl's Moving Castle", 'The Secret in Their Eyes', 'Guardians of the Galaxy Vol. 3', 'Three Billboards Outside Ebbing, Missouri', 'Prisoners', 'Trainspotting', 'The Bridge on the River Kwai', 'Fargo', 'Warrior', 'Gran Torino', 'Catch Me If You Can', 'My Neighbor Totoro', 'Million Dollar Baby', 'Children of Heaven', 'The Gold Rush', 'Blade Runner', 'Klaus', 'Harry Potter and the Deathly Hallows: Part 2', '12 Years a Slave', 'Before Sunrise', 'The Grand Budapest Hotel', 'Ben-Hur', 'On the Waterfront', 'Gone Girl', 'The General', 'Barry Lyndon', 'Wild Strawberries', 'In the Name of the Father', 'The Deer Hunter', 'Hacksaw Ridge', 'The Third Man', 'The Wages of Fear', 'Memories of Murder', 'Sherlock Jr.', 'Wild Tales', 'Mr. Smith Goes to Washington', 'Mad Max: Fury Road', 'Mary and Max', 'Dead Poets Society', 'How to Train Your Dragon', 'Monsters, Inc.', 'The Seventh Seal', 'Jaws', 'Room', 'The Big Lebowski', 'Tokyo Story', 'Ford v Ferrari', 'The Passion of Joan of Arc', 'Hotel Rwanda', 'Rocky', 'Ratatouille', 'Platoon', 'Spotlight', 'Logan', 'The Terminator', 'Jai Bhim', 'Rush', 'Stand by Me', 'Before Sunset', 'Network', 'Into the Wild', 'The Wizard of Oz', 'The Best Years of Our Lives', 'The Exorcist', 'La haine', 'The Incredibles', 'To Be or Not to Be', 'Groundhog Day', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Battle of Algiers', 'The Grapes of Wrath', 'My Father and My Son', "Hachi: A Dog's Tale", 'Pather Panchali', 'The Handmaiden', 'Amores Perros', 'Rebecca', 'Cool Hand Luke', 'The Sound of Music', 'It Happened One Night', 'The 400 Blows', 'Persona', 'The Help', 'Life of Brian', 'The Iron Giant', 'Aladdin', 'Dances with Wolves']

In [61]:
year=[]
for m in movie:
    year.append(m.find('span',class_='secondaryInfo').text[1:-1].strip())
print(year)

['1994', '1972', '2008', '1974', '1957', '1993', '2003', '1994', '2001', '1966', '2023', '1994', '1999', '2002', '2010', '1980', '1999', '1990', '1975', '1995', '1946', '1954', '1991', '1998', '2002', '2014', '1997', '1999', '1977', '1991', '1985', '2001', '2002', '1960', '2019', '1994', '1994', '2000', '1998', '2006', '2014', '2006', '1995', '1942', '1988', '1962', '2011', '1936', '1968', '1988', '1954', '1979', '1931', '1979', '2000', '2012', '1981', '2008', '2006', '1950', '1957', '2018', '1980', '1940', '1957', '2018', '1986', '1999', '2012', '1964', '2009', '2003', '2017', '1984', '1995', '1995', '1981', '2019', '2019', '1997', '1997', '1984', '2016', '2009', '1952', '1963', '2000', '2018', '2010', '1983', '1985', '2004', '1968', '2012', '1992', '1962', '1941', '1931', '1952', '1959', '1960', '1958', '2001', '1944', '1971', '1987', '2020', '1983', '2010', '1995', '2009', '1962', '1973', '2011', '1927', '1997', '1988', '1989', '2000', '1976', '1948', '2007', '2019', '2016', '2004', '2022', '1965', '2005', '1921', '1959', '2020', '2013', '1950', '2018', '1961', '1985', '1998', '1995', '2007', '2006', '1992', '2010', '1999', '1993', '2001', '1948', '1961', '1975', '2007', '2003', '1963', '1950', '1982', '2003', '2021', '1980', '1974', '1980', '2005', '1939', '1954', '2015', '1998', '2004', '2009', '2023', '2017', '2013', '1996', '1957', '1996', '2011', '2008', '2002', '1988', '2004', '1997', '1925', '1982', '2019', '2011', '2013', '1995', '2014', '1959', '1954', '2014', '1926', '1975', '1957', '1993', '1978', '2016', '1949', '1953', '2003', '1924', '2014', '1939', '2015', '2009', '1989', '2010', '2001', '1957', '1975', '2015', '1998', '1953', '2019', '1928', '2004', '1976', '2007', '1986', '2015', '2017', '1984', '2021', '2013', '1986', '2004', '1976', '2007', '1939', '1946', '1973', '1995', '2004', '1942', '1993', '2003', '1966', '1940', '2005', '2009', '1955', '2016', '2000', '1940', '1967', '1965', '1934', '1959', '1966', '2011', '1979', '1999', '1992', '1990']

In [62]:
rating=[]
for i in s.find_all('td',class_='ratingColumn imdbRating'):
    rating.append(i.text.strip())
print(rating)

['9.2', '9.2', '9.0', '9.0', '9.0', '8.9', '8.9', '8.8', '8.8', '8.8', '8.8', '8.8', '8.7', '8.7', '8.7', '8.7', '8.7', '8.7', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0']

In [65]:
import pandas as pd

In [68]:
df=pd.DataFrame({"movie title":title,'Release year':year, 'Rating':rating})
df.head()

                movie title Release year Rating
0  The Shawshank Redemption         1994    9.2
1             The Godfather         1972    9.2
2           The Dark Knight         2008    9.0
3     The Godfather Part II         1974    9.0
4              12 Angry Men         1957    9.0